changes
Signed-off-by: Humair Khan <HumairAK@users.noreply.github.com>

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -24,7 +24,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
+        k8s_version: [ "v1.31.0" ]
     name: Initialization tests v1 - K8s ${{ matrix.k8s_version }}
     steps:
       - name: Checkout code
@@ -74,7 +74,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
+        k8s_version: [ "v1.31.0" ]
     name: Initialization tests v2 - K8s ${{ matrix.k8s_version }}
     steps:
       - name: Checkout code
@@ -124,7 +124,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
+        k8s_version: [ "v1.31.0" ]
     name: API integration tests v1 - K8s ${{ matrix.k8s_version }}
     steps:
       - name: Checkout code
@@ -180,8 +180,8 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        pipeline_store: [ "database", "kubernetes" ]
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
+        pipeline_store: [ "database" ]
+        k8s_version: [ "v1.31.0" ]
     name: API integration tests v2 - K8s with ${{ matrix.pipeline_store }} ${{ matrix.k8s_version }}
     steps:
       - name: Checkout code
@@ -235,63 +235,63 @@ jobs:
           name: kfp-api-integration-tests-v2-artifacts-k8s-${{ matrix.k8s_version }}-${{ matrix.pipeline_store }}
           path: /tmp/tmp*/*
 
-  api-integration-tests-v2-with-proxy:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        k8s_version: [ "v1.31.0" ]
-    name: API integration tests v2 with proxy - K8s ${{ matrix.k8s_version }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9
-
-      - name: Create KFP cluster
-        id: create-kfp-cluster
-        uses: ./.github/actions/kfp-cluster
-        with:
-          k8s_version: ${{ matrix.k8s_version }}
-          proxy: 'true'
-        continue-on-error: true
-
-      - name: Forward API port
-        id: forward-api-port
-        if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
-        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888
-        continue-on-error: true
-
-      - name: Forward MLMD port
-        id: forward-mlmd-port
-        if: ${{ steps.forward-api-port.outcome == 'success' }}
-        run: kubectl -n kubeflow port-forward svc/metadata-grpc-service 8080:8080 &
-        continue-on-error: true
-
-      - name: API integration tests v2
-        id: tests
-        if: ${{ steps.forward-mlmd-port.outcome == 'success' }}
-        working-directory: ./backend/test/v2/integration
-        run: go test -v ./... -namespace kubeflow -args -runIntegrationTests=true -useProxy=true
-        env:
-          PULL_NUMBER: ${{ github.event.pull_request.number }}
-        continue-on-error: true
-
-      - name: Collect failed logs
-        if: ${{ steps.create-kfp-cluster.outcome != 'success' || steps.forward-api-port.outcome != 'success' || steps.tests.outcome != 'success' }}
-        run: |
-          ./.github/resources/scripts/collect-logs.sh --ns squid --output /tmp/tmp_squid_pod_log.txt
-          ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
-          exit 1
-
-      - name: Collect test results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: kfp-api-integration-tests-v2-with-proxy-artifacts-k8s-${{ matrix.k8s_version }}
-          path: /tmp/tmp*/*
+#  api-integration-tests-v2-with-proxy:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        k8s_version: [ "v1.31.0" ]
+#    name: API integration tests v2 with proxy - K8s ${{ matrix.k8s_version }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: 3.9
+#
+#      - name: Create KFP cluster
+#        id: create-kfp-cluster
+#        uses: ./.github/actions/kfp-cluster
+#        with:
+#          k8s_version: ${{ matrix.k8s_version }}
+#          proxy: 'true'
+#        continue-on-error: true
+#
+#      - name: Forward API port
+#        id: forward-api-port
+#        if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
+#        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888
+#        continue-on-error: true
+#
+#      - name: Forward MLMD port
+#        id: forward-mlmd-port
+#        if: ${{ steps.forward-api-port.outcome == 'success' }}
+#        run: kubectl -n kubeflow port-forward svc/metadata-grpc-service 8080:8080 &
+#        continue-on-error: true
+#
+#      - name: API integration tests v2
+#        id: tests
+#        if: ${{ steps.forward-mlmd-port.outcome == 'success' }}
+#        working-directory: ./backend/test/v2/integration
+#        run: go test -v ./... -namespace kubeflow -args -runIntegrationTests=true -useProxy=true
+#        env:
+#          PULL_NUMBER: ${{ github.event.pull_request.number }}
+#        continue-on-error: true
+#
+#      - name: Collect failed logs
+#        if: ${{ steps.create-kfp-cluster.outcome != 'success' || steps.forward-api-port.outcome != 'success' || steps.tests.outcome != 'success' }}
+#        run: |
+#          ./.github/resources/scripts/collect-logs.sh --ns squid --output /tmp/tmp_squid_pod_log.txt
+#          ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
+#          exit 1
+#
+#      - name: Collect test results
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: kfp-api-integration-tests-v2-with-proxy-artifacts-k8s-${{ matrix.k8s_version }}
+#          path: /tmp/tmp*/*
 
   api-integration-tests-v2-with-cache-disabled:
     runs-on: ubuntu-latest
@@ -350,68 +350,68 @@ jobs:
           name: kfp-api-integration-tests-v2-with-cache-disabled-artifacts-k8s-${{ matrix.k8s_version }}
           path: /tmp/tmp*/*
 
-  frontend-integration-test:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
-    name: Frontend Integration Tests - K8s ${{ matrix.k8s_version }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9
-
-      - name: Create KFP cluster
-        id: create-kfp-cluster
-        uses: ./.github/actions/kfp-cluster
-        with:
-          k8s_version: ${{ matrix.k8s_version }}
-        continue-on-error: true
-
-      - name: Forward API port
-        id: forward-api-port
-        if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
-        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888
-        continue-on-error: true
-
-      - name: Forward Frontend port
-        id: forward-frontend-port
-        if: ${{ steps.forward-api-port.outcome == 'success' }}
-        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline-ui" 3000 3000
-        continue-on-error: true
-
-      - name: Build frontend integration tests image
-        working-directory: ./test/frontend-integration-test
-        run: docker build . -t kfp-frontend-integration-test:local
-
-      - name: Frontend integration tests
-        id: tests
-        if: ${{ steps.forward-frontend-port.outcome == 'success' }}
-        run: docker run --net=host kfp-frontend-integration-test:local --remote-run true
-        continue-on-error: true
-
-      - name: Collect failed logs
-        if: ${{ steps.create-kfp-cluster.outcome != 'success' || steps.forward-api-port.outcome != 'success' || steps.forward-frontend-port.outcome != 'success' || steps.tests.outcome != 'success' }}
-        run: |
-          ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
-          exit 1
-
-      - name: Collect test results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: kfp-frontend-integration-test-artifacts-k8s-${{ matrix.k8s_version }}
-          path: /tmp/tmp*/*
+#  frontend-integration-test:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        k8s_version: [ "v1.31.0" ]
+#    name: Frontend Integration Tests - K8s ${{ matrix.k8s_version }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: 3.9
+#
+#      - name: Create KFP cluster
+#        id: create-kfp-cluster
+#        uses: ./.github/actions/kfp-cluster
+#        with:
+#          k8s_version: ${{ matrix.k8s_version }}
+#        continue-on-error: true
+#
+#      - name: Forward API port
+#        id: forward-api-port
+#        if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
+#        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888
+#        continue-on-error: true
+#
+#      - name: Forward Frontend port
+#        id: forward-frontend-port
+#        if: ${{ steps.forward-api-port.outcome == 'success' }}
+#        run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline-ui" 3000 3000
+#        continue-on-error: true
+#
+#      - name: Build frontend integration tests image
+#        working-directory: ./test/frontend-integration-test
+#        run: docker build . -t kfp-frontend-integration-test:local
+#
+#      - name: Frontend integration tests
+#        id: tests
+#        if: ${{ steps.forward-frontend-port.outcome == 'success' }}
+#        run: docker run --net=host kfp-frontend-integration-test:local --remote-run true
+#        continue-on-error: true
+#
+#      - name: Collect failed logs
+#        if: ${{ steps.create-kfp-cluster.outcome != 'success' || steps.forward-api-port.outcome != 'success' || steps.forward-frontend-port.outcome != 'success' || steps.tests.outcome != 'success' }}
+#        run: |
+#          ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
+#          exit 1
+#
+#      - name: Collect test results
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: kfp-frontend-integration-test-artifacts-k8s-${{ matrix.k8s_version }}
+#          path: /tmp/tmp*/*
 
   basic-sample-tests:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        k8s_version: [ "v1.29.2", "v1.31.0" ]
+        k8s_version: [ "v1.31.0" ]
     name: Basic Sample Tests - K8s ${{ matrix.k8s_version }}
     steps:
       - name: Checkout code
@@ -435,28 +435,14 @@ jobs:
         run: ./.github/resources/scripts/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888
         continue-on-error: true
 
+      - name: Install protobuf dependencies & kfp-pipeline-spec
+        if: ${{ steps.forward-api-port.outcome == 'success' }}
+        id: install-protobuf-deps
+        uses: ./.github/actions/protobuf
+
       - name: Install prerequisites
         if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
         run: pip3 install -r ./test/sample-test/requirements.txt
-
-      - name: Install protobuf-compiler
-        id: install-protobuf-compiler
-        run: sudo apt update && sudo apt install -y protobuf-compiler
-
-      - name: Install Wheel
-        id: install-wheel
-        run: pip3 install wheel==0.42.0 setuptools
-
-      - name: Generate API proto files
-        working-directory: ./api
-        run: make python
-      
-      - name: Install local kfp from source
-        run: python3 -m pip install -I sdk/python
-
-      - name: Install kfp-pipeline-spec from source
-        run: |
-          python3 -m pip install -I api/v2alpha1/python
 
       - name: Basic sample tests - sequential
         if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
